# Generated by Django 3.1.1 on 2020-09-27 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='userGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='game.users')),
            ],
            options={
                'db_table': 'userGame',
            },
        ),
        migrations.CreateModel(
            name='gameMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('column', models.IntegerField()),
                ('row', models.IntegerField()),
                ('colour', models.CharField(max_length=20)),
                ('userGameId', models.ForeignKey(db_column='userGameId', on_delete=django.db.models.deletion.CASCADE, to='game.usergame')),
            ],
            options={
                'db_table': 'gameMoves',
            },
        ),
    ]
